# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install python packages
      run: pip3 install --quiet poetry && poetry install --with dev --no-interaction
    - name: black
      run: poetry run black --check futaba
